apiVersion: apps/v1
kind: Deployment
metadata:
  name: eldocam-frontend
  namespace: eldocam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eldocam-frontend
  template:
    metadata:
      labels:
        app: eldocam-frontend
    spec:
      containers:
      - name: nginx
        image: ghcr.io/sebbemercier/eldocam-frontend:latest  # ‚Üê Image de GitHub Actions
        ports:
        - containerPort: 80
