apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: eldocam-https
  namespace: eldocam
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`eldocam.com`) || Host(`www.eldocam.com`) || Host(`eldocam.be`) || Host(`www.eldocam.be`)
    kind: Rule
    services:
    - name: eldocam-frontend
      port: 80
  tls:
    certResolver: letsencrypt
