apiVersion: v1
kind: Service
metadata:
  name: eldocam-frontend
  namespace: eldocam
  labels:
    app: eldocam
spec:
  selector:
    app: eldocam
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
